this {
    scope.shape: rectangle
    push_start.shape: rectangle
    push_end.shape: rectangle
    pop_start.shape: rectangle
    pop_end.shape: rectangle
}

nodes: {
    scope.shape: circle
    push.shape: circle
    pop.shape: circle
}

(this.push_start -- nodes.push).style.stroke: red
(this.push_end -- nodes.push).style.stroke: red
(this.scope -- nodes.scope).style.stroke: red

nodes.push -> nodes.scope

this.pop_start -> nodes.pop
this.pop_end -> nodes.pop

