@startuml

namespace node {
    entity scope
    entity push_start
    entity push_end
    entity pop_start
    entity pop_end
}

namespace scope {
    entity scope
    entity push_start
    entity push_end
    entity pop_start
    entity pop_end
}

namespace identifier {
    entity scope
    entity push_start
    entity push_end
    entity pop_start
    entity pop_end
}

scope.scope ---> scope.pop_start
scope.push_end ---> scope.scope
identifier.scope ---> identifier.pop_start
identifier.push_end ---> identifier.scope
scope.push_end ---> identifier.push_start
identifier.pop_end ---> scope.pop_start
node.push_end ---> node.scope
node.scope ---> node.pop_start

node.scope - scope.scope
node.pop_start - scope.pop_start
node.push_end - identifier.push_end
node.push_start - scope.push_start
node.pop_end - identifier.pop_end
scope.pop_end - scope.pop_start
scope.push_start - scope.push_end
identifier.pop_end - identifier.pop_start
identifier.push_start - identifier.push_end
@enduml
